### ISSUE TITLE
object detection support

### ISSUE THREAD

**Issue by skrish13** [epic-kitchens/epic-lib#14]
Hi,

Please correct me if im wrong, but currently there isnt any support for object detection experiments in the library right?

**Comment by GinaJemy** [comment]
Can you provide any instructions on using the dataset and annotations for training an object detector such as YOLO on your dataset ?
Thanks

**Comment by willprice** [comment]
The training annotations are accessible through [`epic_kitchens.meta.training_object_labels()`](https://epic-kitchens.readthedocs.io/en/latest/epic_kitchens.html#epic_kitchens.meta.training_object_labels) but that is the extent of support provided by this library. The frames are annotated with active object (i.e. the object is participating in the current action) annotations every 1/2 second (every 30 frames). I'd suggest using these annotations in combination with the instructions provided for supporting new datasets by YOLOv3/CenterNet/FasterRCNN/<YourFavouriteObjectDetector>. I sadly don't have any experience with these. Good luck :+1:
