### ISSUE TITLE
Add metrics code

### ISSUE THREAD

**Issue by willprice** [epic-kitchens/epic-lib#42]
Provide methods to compute:
- [x] Top-1 accuracy
   - [x] verbs
   - [x] nouns
   - [x] actions
- [x] Top-5 accuracy
   - [x] verbs
   - [x] nouns
   - [x] actions
- [x] Per-class recall on many shot classes
   - [x] verbs
   - [x] nouns
   - [x] actions
- [x] Per-class precision on many shot classes
   - [x] verbs
   - [x] nouns
   - [x] actions

Given a groundtruth data frame containing the correct verb, noun, and action for a given action segment (identified by UID)

**Comment by kylemin** [comment]
Do you have a plan to release the metrics code?

**Comment by willprice** [comment]
I do indeed, but it's unlikely I'll get around to it before the ICCV deadline.

**Comment by willprice** [comment]
Released in v1.7.0 now on PyPI. `pip install -U epic-kitchens` to upgrade :D
