### ISSUE TITLE
Extract flow images for every rgb image

### ISSUE THREAD

**Issue by notabigfish** [epic-kitchens/epic-lib#78]
Hi,
I've use the following method to extract optical flow and RGB images:
```
$ python -m epic_kitchens.preprocessing.split_segments \
    P01 \
    root_dir/P01 \
    output_dir/P01 \
    EPIC_train_action_labels.pkl \
    flow \
    --fps 60 \
    --frame-format 'frame_%010d.jpg'

```
But it seems that optical flow images are extracted every two RGB images. Is it possible to extract optical flow image for every RGB image? Thank you!

**Comment by willprice** [comment]
This command is simply for splitting up a set of frames extracted from an entire video into frames grouped by clip, it doesn't compute anything, it's simply symlinking frames from one directory to another - if you want to use optical flow computed in a different way to the way we have, you'll to use a tool like https://github.com/feichtenhofer/gpu_flow
